name: shared
description: "Shared package for MoneyTracker app"
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get_it: ^9.1.1
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
