name: shared
description: "Shared package for MoneyTracker app"
version: 0.0.1
publish_to: none
resolution: workspace

executables:
  create_feature:

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  get_it: ^9.1.1
  hive_ce_flutter: ^2.3.3
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  ua_client_hints: ^1.4.1
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  synchronized: ^3.4.0
  easy_localization: ^3.0.8
  fpdart: ^1.2.0
  hive_ce: ^2.15.1
  json_annotation: ^4.9.0
  go_router: ^17.0.0
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.12.0
  flutter_hooks: ^0.21.3+1
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  hive_ce_generator: ^1.10.0
