name: auth
description: auth feature package for Money Tracker application.
version: 0.0.1
publish_to: "none"
resolution: "workspace"

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../shared
  ui:
    path: ../ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1

flutter:
  assets:
    - ./assets/translations/
