name: ui
description: "UI components for MoneyTracker app"
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0

flutter:
  assets:
    - ./assets/images/
    - ./assets/translations/
  fonts:
    - family: ibmPlexSansThai
      fonts:
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Thin.ttf
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-ExtraLight.ttf
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Light.ttf
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Regular.ttf
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Medium.ttf
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-SemiBold.ttf
        - asset: ./assets/fonts/ibm_plex_sans_thai/IBMPlexSansThai-Bold.ttf

flutter_gen:
  output: ./lib/generated
  line_length: 120
  assets:
    enabled: true
    outputs:
      style: dot-delimiter
      class_name: UiAssets
      package_parameter_enabled: true
    exclude:
      - assets/translations/**
